
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

# Current workaround to test on Python 3.7
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt
  - pip install -r optional-requirements.txt
  - pip install pytest-cov
  - pip install codecov

script:
  - py.test --cov=./

after_success:
  - codecov
